name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What would you like to build?
  - type: textarea
    attributes:
      label: Why is this valuable?
